---

- include: "redhat.yml"
  when: ansible_os_family == "RedHat"

- include: "debian.yml"
  when: ansible_os_family == "Debian"

- name: Set OSSEC deploy facts for RedHat
  set_fact:
    ossec_agent_config: ossec-agent.conf
    ossec: ossec-hids
  when: ansible_os_family == "RedHat"

- name: Set OSSEC deploy facts for Debian
  set_fact:
    ossec_agent_config: ossec.conf
    ossec: ossec
  when: ansible_os_family == "Debian"

# Bug fix: https://github.com/ossec/ossec-hids/issues/865
- name: Create OSSEC directories
  file: path={{item}} state=directory
  with_items:
    -  /var/ossec/logs/archives
  when: ansible_distribution == "Debian"

- name: Configure OSSEC
  template: src=agent.conf.j2 dest=/var/ossec/etc/{{ ossec_agent_config }} owner=root group=root mode=0644
  notify: restart ossec-agent

- name: Configure Active Response
  copy: src=active-response/ dest=/var/ossec/active-response/bin owner=root group=ossec mode=0550
  notify: restart ossec-agent

- name: Configure OSSEC Agent
  command: /var/ossec/bin/agent-auth -m {{ ossec_server_hostname }}
  args:
    creates: /var/ossec/etc/client.keys
  notify: restart ossec-agent

- name: Enable ossec-agent
  service: name={{ ossec }} enabled=yes
- name: Start ossec-agent
  service: name={{ ossec }} state=started
