---

- name: Install Unbound
  yum: name=unbound state=present

- name: Configure Unbound
  template: src=unbound.conf.j2 dest=/etc/unbound/unbound.conf owner=root group=root mode=0644
  notify:
    - restart unbound
