---

- name: Install RHEL6 CIS Root Checks
  get_url:
    url: https://raw.githubusercontent.com/ossec/ossec-hids/master/src/rootcheck/db/cis_rhel6_linux_rcl.txt
    dest: /var/ossec/etc/shared/cis_rhel6_linux_rcl.txt
    mode: 0660
    owner: root
    group: ossec

- name: Install RHEL7 CIS Root Checks  
  get_url:
    url: https://raw.githubusercontent.com/ossec/ossec-hids/master/src/rootcheck/db/cis_rhel7_linux_rcl.txt
    dest: /var/ossec/etc/shared/cis_rhel7_linux_rcl.txt
    mode: 0660
    owner: root
    group: ossec 

- name: Set Distribution CIS filename for Debian/Ubuntu
  set_fact:
    cis_distribution_filename: cis_debian_linux_rcl.txt
  when: ansible_os_family == "Debian"

- name: Set Distribution CIS filename for RHEL5
  set_fact:
    cis_distribution_filename: cis_rhel5_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "5"

- name: Set Distribution CIS filename for RHEL6
  set_fact:
    cis_distribution_filename: cis_rhel6_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6"

- name: Set Distribution CIS filename for RHEL7
  set_fact:
    cis_distribution_filename: cis_rhel7_linux_rcl.txt
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
