---

- name: Check if ossec-csyslog is enabled
  shell: "/var/ossec/bin/ossec-control status || true"
  register: ossec_status
  changed_when: False

- name: Syslog Output Settings
  debug: msg="{{ ossec_server_config['syslog'] }}"
  when: ossec_server_config['syslog'] is defined

- name: Enable client-syslog
  shell: "/var/ossec/bin/ossec-control enable client-syslog"
  when: ossec_server_config['syslog'] is defined and ('csyslogd' not in ossec_status.stdout or 'csyslogd not running' in ossec_status.stdout)
  notify: restart ossec-server

- name: Disable client-syslog
  shell: "/var/ossec/bin/ossec-control disable client-syslog"
  when: ossec_server_config['syslog'] is not defined and 'csyslogd not running' in ossec_status.stdout
  notify: restart ossec-server
