---
- name: Set hostname
  hostname: name={{ inventory_hostname }}
  when: ansible_distribution == "Ubuntu"
  notify:
    - restart hostname

- name: restart hostname
  service: name=hostname state=restarted
  when: ansible_distribution == "Ubuntu"

- name: Set hostname
  shell: hostnamectl set-hostname {{ inventory_hostname }}
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
