---

- name: Add docker repo script
  copy: src=add-docker-repo.sh dest=/usr/local/bin owner=root group=root mode=0755

- name: Add docker repositories
  shell: /usr/local/bin/add-docker-repo.sh
  args:
    creates: /etc/apt/sources.list.d/docker.list
  when: ansible_pkg_mgr == "apt"

- name: Add docker repositories
  shell: /usr/local/bin/add-docker-repo.sh
  args:
    creates: /etc/yum.repos.d/docker-main.repo
  when: ansible_pkg_mgr == "yum"

- name: Install docker
  apt: name=docker-engine state=present update_cache=yes
  when: ansible_pkg_mgr == "apt"

- name: Install docker
  yum: name=docker-engine state=present update_cache=yes
  when: ansible_pkg_mgr == "yum"

- name: Install PIP
  yum: name={{ item }} state=present
  with_items:
    - python-pip
  when: ansible_pkg_mgr == "yum"

- name: Install docker-py
  pip: name=docker-py

# enable service
- name: Enable docker
  service: name=docker enabled=yes
- name: Start docker
  service: name=docker state=started
